# Generated by Django 3.0.14 on 2021-11-13 01:56

import course.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0020_question_question_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='submission_analytics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ans_file', course.fields.JSONField(default=dict)),
                ('lines', models.IntegerField()),
                ('blank_lines', models.IntegerField()),
                ('comment_lines', models.IntegerField()),
                ('import_lines', models.IntegerField()),
                ('cc', models.IntegerField()),
                ('method', models.IntegerField()),
                ('operator', models.IntegerField()),
                ('operand', models.IntegerField()),
                ('unique_operator', models.IntegerField()),
                ('unique_operand', models.IntegerField()),
                ('vocab', models.IntegerField()),
                ('size', models.IntegerField()),
                ('vol', models.DecimalField(decimal_places=4, max_digits=8)),
                ('difficulty', models.DecimalField(decimal_places=4, max_digits=8)),
                ('effort', models.DecimalField(decimal_places=4, max_digits=8)),
                ('error', models.DecimalField(decimal_places=4, max_digits=8)),
                ('test_time', models.DecimalField(decimal_places=4, max_digits=8)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Question')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.Submission')),
                ('uqj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.UserQuestionJunction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
