# Generated by Django 3.0.14 on 2022-02-13 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='javaquestionanalytics',
            old_name='cc',
            new_name='cyclomatic_complexity',
        ),
        migrations.RenameField(
            model_name='parsonsquestionanalytics',
            old_name='cc',
            new_name='cyclomatic_complexity',
        ),
    ]
