# Generated by Django 3.0.14 on 2022-02-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventanalytics',
            name='total_submissions',
            field=models.IntegerField(default=0),
        ),
    ]
