# Generated by Django 3.0.14 on 2021-11-13 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission_analytics',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='submission_analytics',
            name='effort',
        ),
        migrations.RemoveField(
            model_name='submission_analytics',
            name='error',
        ),
        migrations.RemoveField(
            model_name='submission_analytics',
            name='size',
        ),
        migrations.RemoveField(
            model_name='submission_analytics',
            name='test_time',
        ),
        migrations.RemoveField(
            model_name='submission_analytics',
            name='unique_operand',
        ),
        migrations.RemoveField(
            model_name='submission_analytics',
            name='unique_operator',
        ),
        migrations.RemoveField(
            model_name='submission_analytics',
            name='vocab',
        ),
        migrations.RemoveField(
            model_name='submission_analytics',
            name='vol',
        ),
    ]
