# Generated by Django 3.0.14 on 2022-02-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_eventanalytics_total_submissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanalytics',
            name='correct_num',
            field=models.IntegerField(default=0),
        ),
    ]
