# Generated by Django 3.0.14 on 2021-11-13 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20211112_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission_analytics',
            name='difficulty',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='submission_analytics',
            name='effort',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='submission_analytics',
            name='error',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='submission_analytics',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission_analytics',
            name='test_time',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='submission_analytics',
            name='unique_operand',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission_analytics',
            name='unique_operator',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission_analytics',
            name='vocab',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission_analytics',
            name='vol',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='submission_analytics',
            name='blank_lines',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submission_analytics',
            name='cc',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submission_analytics',
            name='comment_lines',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submission_analytics',
            name='import_lines',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submission_analytics',
            name='lines',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submission_analytics',
            name='method',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submission_analytics',
            name='operand',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submission_analytics',
            name='operator',
            field=models.IntegerField(default=0),
        ),
    ]
