# Generated by Django 3.0.14 on 2021-11-13 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_auto_20211112_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission_analytics',
            name='ans',
            field=models.CharField(default='n/a', max_length=255),
        ),
    ]
