# Generated by Django 3.0.14 on 2022-02-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_questionanalytics_correct_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanalytics',
            name='assigned_difficulty',
            field=models.CharField(default='EASY', max_length=10),
        ),
    ]
