# Generated by Django 3.0.14 on 2021-11-13 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_submission_analytics_ans'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission_analytics',
            name='submission_type',
            field=models.CharField(default='n/a', max_length=255),
        ),
    ]
