# Generated by Django 3.0.14 on 2022-03-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_questionanalytics_assigned_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanalytics',
            name='junit_template',
            field=models.TextField(default='n/a'),
        ),
    ]
