# Generated by Django 3.0.14 on 2022-03-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_questionanalytics_junit_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='javaquestionanalytics',
            name='space',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='javaquestionanalytics',
            name='space_stdev',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='javaquestionanalytics',
            name='test_time_stdev',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='javasubmissionanalytics',
            name='space',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='parsonsquestionanalytics',
            name='space',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='parsonsquestionanalytics',
            name='space_stdev',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='parsonsquestionanalytics',
            name='test_time_stdev',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='parsonssubmissionanalytics',
            name='space',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
    ]
