# Generated by Django 3.0.14 on 2021-11-13 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_submission_analytics_submission_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission_analytics',
            name='user',
        ),
        migrations.AddField(
            model_name='submission_analytics',
            name='first_name',
            field=models.CharField(default='n/a', max_length=255),
        ),
        migrations.AddField(
            model_name='submission_analytics',
            name='last_name',
            field=models.CharField(default='n/a', max_length=255),
        ),
        migrations.AddField(
            model_name='submission_analytics',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
