# Generated by Django 3.0.14 on 2022-03-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_auto_20220307_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsonsquestionanalytics',
            name='space',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='parsonssubmissionanalytics',
            name='space',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
