# Generated by Django 3.0.14 on 2022-01-29 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0011_merge_20211116_1744'),
        ('analytics', '0007_auto_20220124_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAnalytics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('high_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('lowest_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('avg_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('avg_score_st_dev', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('num_participants', models.IntegerField(default=0)),
                ('course_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='canvas.CanvasCourse')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canvas.Event')),
            ],
        ),
    ]
