# Generated by Django 3.0.14 on 2022-01-29 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_eventanalytics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventanalytics',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='eventanalytics',
            old_name='event_id',
            new_name='event',
        ),
    ]
