# Generated by Django 3.0.14 on 2022-03-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_auto_20220307_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='javaquestionanalytics',
            name='space',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='javaquestionanalytics',
            name='space_stdev',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='javaquestionanalytics',
            name='test_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='javaquestionanalytics',
            name='test_time_stdev',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='parsonsquestionanalytics',
            name='space',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='parsonsquestionanalytics',
            name='space_stdev',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='parsonsquestionanalytics',
            name='test_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='parsonsquestionanalytics',
            name='test_time_stdev',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
